--EXPERIMENT NO. 3: DDL COMMANDS  AND CONSTRAINTS--
--CREATE A  TABLE EMP--
CREATE TABLE EMP(EMPNO INT(4) PRIMARY KEY, ENAME CHAR(10), HIREDATE DATE, SALARY INT(5), COMMISSION INT(5));

--INSERT OF DATA--
INSERT INTO EMP(EMPNO,ENAME,HIREDATE,SALARY) VALUES(101,'RAMESH','1980-01-17',5000);
   INSERT INTO EMP(EMPNO,ENAME,HIREDATE,SALARY,COMMISSION) VALUES(102,'AJAY','1985-07-05',5000,500);
   INSERT INTO EMP(EMPNO,ENAME,HIREDATE,SALARY) VALUES(103,'RAVI','1981-08-12',1500);
   INSERT INTO EMP(EMPNO,ENAME,HIREDATE,SALARY,COMMISSION) VALUES(104,'NIKESH','1983-03-03',3000,700);
   INSERT INTO EMP(EMPNO,ENAME,HIREDATE,SALARY) VALUES(105,'RAVI','1985-07-05',3000);
   SELECT * FROM EMP;

--2.MODIFYING THE STRUCTURE OF TABLES --
-- 1. ADD NEW COLUMNS: SAL NUMBER(7.2)
ALTER TABLE EMP ADD SAL INT;

-- 2. DROPPING A COLUMN FROM A TABLE:SAL 
ALTER TABLE EMP DROP COLUMN SAL;

-- 3. MODIFYING EXISTING COLUMN:ENAME VARCHAR2(15) 
ALTER TABLE EMP MODIFY ENAME VARCHAR(15);

-- 4. RENAMING THE TABLES: EMP TO EMP1;
RENAME TABLE EMP TO EMP1;

-- 5. TRUNCATING THE TABLES:EMP1
TRUNCATE TABLE EMP1;

-- 6 DESTROYING TABLES:EMP
DROP TABLE EMP1;

--3.CREATE A TABLE STUD--
CREATE TABLE STUD(SNAME VARCHAR(20) PRIMARY KEY, ROLLNO INT NOT NULL, DOB DATE NOT NULL);
SELECT * FROM STUD;

--4.CREATE A TABLE STUDENT--
CREATE TABLE STUDENT (REGNO INT, MARK INT(3) CONSTRAINT B CHECK (MARK >=0 AND MARK <=100));
SELECT * FROM STUDENT;

--IN TABLE STUDENT ADD CHECK CONSTRAINT(LENGTH(REGNO<=4))--
ALTER TABLE STUDENT ADD REGNO CHECK (LENGTH(REGNO<=4));

--5.CREATE A TABLE CUST--
CREATE TABLE CUST(CUSTID NUMBER(6) UNIQUE, NAME CHAR(10));
                 